(define (problem Random-5x1)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4 - block)
    (:init (arm-clear) (clear b4) (on b0 b2) (on b2 b1) (on b3 b0) (on b4 b3) (on-table b1))
    (:goal (and (clear b4) (on b2 b1) (on b1 b0) (arm-clear) (on b4 b3) (on b3 b2) (on-table b0)))
)
