(define (problem Random-6x1)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4 b5 - block r1 - arm)
    (:init
        (arm r1)
        (block b0) (block b1) (block b2) (block b3) (block b4) (block b5)
        (arm-clear r1)
        (clear b2)
        (on b0 b1)
        (on b2 b4)
        (on b3 b0)
        (on b4 b5)
        (on b5 b3)
        (on-table b1)
    )
    (:goal (and (on b2 b1) (arm-clear r1) (on b4 b3) (on b5 b4) (clear b5) (on b1 b0) (on b3 b2) (on-table b0)))
)
