(define
  (domain blocksworld)
  (:requirements :strips :typing)
  (:types block arm)
  (:predicates
    (on ?a - block ?b - block)
    (on-table ?b - block)
    (holding ?a - arm ?b - block)
    (clear ?b - block)
    (arm-clear ?a - arm)
    (block ?b - block)
    (arm ?a - arm)
  )
  (:action pick
    :parameters (?a - arm ?b - block)
    :precondition (and (arm ?a) (block ?b) (on-table ?b) (clear ?b) (arm-clear ?a))
    :effect (and
      (not (arm-clear ?a))
      (not (on-table ?b))
      (not (clear ?b))
      (holding ?a ?b)
    )
  )
  (:action place
    :parameters (?a - arm ?b - block)
    :precondition (and (holding ?a ?b))
    :effect (and
      (arm-clear ?a)
      (on-table ?b)
      (clear ?b)
      (not (holding ?a ?b))
    )
  )
  (:action pick-from
    :parameters (?a - arm ?b1 - block ?b2 - block)
    :precondition (and (on ?b1 ?b2) (clear ?b1) (arm-clear ?a))
    :effect (and
      (not (arm-clear ?a))
      (not (on ?b1 ?b2))
      (holding ?a ?b1)
      (not (clear ?b1))
      (clear ?b2)
    )
  )
  (:action place-on
    :parameters (?a - arm ?b1 - block ?b2 - block)
    :precondition (and (clear ?b2) (holding ?a ?b1))
    :effect (and
      (arm-clear ?a)
      (on ?b1 ?b2)
      (not (holding ?a ?b1))
      (clear ?b1)
      (not (clear ?b2))
    )
  )
)
